version: '2'

services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    restart: always
    user: root
    privileged: true
    networks:
      - jenkins
    ports:
      - 9090:8080
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  jenkins: